repos:
  - repo: local
    hooks:
      - id: lint-staged
        name: lint-staged
        entry: npx lint-staged
        language: system
        pass_filenames: false
      - id: npm-lint
        name: npm run lint
        entry: npm
        args: ['run', 'lint']
        language: system
        pass_filenames: false
      - id: npm-test-forbid-only
        name: npm test -- --forbid-only
        entry: npm
        args: ['test', '--', '--forbid-only']
        language: system
        pass_filenames: false
